services:
  - type: web
    name: my-nextjs-app               # Change this to your desired service name
    env: node                         # Environment type
    buildCommand: npm run build        # Command to build your Next.js app
    startCommand: npm run start        # Command to start your Next.js app
    autoDeploy: true                   # Automatically deploy on push
    branch: main                       # Specify the branch to deploy from
